### ISSUE TITLE
Track terminals aren't working

### ISSUE THREAD

**Issue by davidwengier** [davidwengier/trains2#11]
Pretty sure we used to draw track terminals when there weren't connections. That seems gone now??

Maybe they were never there and I'm crazy, but it would still look better.

**Comment by ScottHolden** [comment]
Think this is a regression of the sprite implementation, I'll take a peek tonight/tomorrow :)

**Comment by ScottHolden** [comment]
Ok, so got bored on a conference call and did it now :P
